package constants

// Provider names for routing
const (
	ProviderAnyScale         = "AnyScale"
	ProviderCentML           = "Cent-ML"
	ProviderHuggingFace      = "HuggingFace"
	ProviderHyperbolic       = "Hyperbolic"
	ProviderHyperbolic2      = "Hyperbolic 2"
	ProviderLepton           = "Lepton"
	ProviderLynn             = "Lynn"
	ProviderLynn2            = "Lynn 2"
	ProviderMancer           = "Mancer"
	ProviderMancer2          = "Mancer 2"
	ProviderModal            = "Modal"
	ProviderOctoAI           = "OctoAI"
	ProviderRecursal         = "Recursal"
	ProviderReflection       = "Reflection"
	ProviderReplicate        = "Replicate"
	ProviderSambaNova        = "SambaNova"
	ProviderSambaNova2       = "SambaNova 2"
	ProviderSFCompute        = "SF Compute"
	ProviderTogether         = "Together"
	ProviderTogether2        = "Together 2"
	Provider01AI             = "01.AI"
	ProviderAI21             = "AI21"
	ProviderAionLabs         = "AionLabs"
	ProviderAlibaba          = "Alibaba"
	ProviderAmazonBedrock    = "Amazon Bedrock"
	ProviderAnthropic        = "Anthropic"
	ProviderAtlasCloud       = "AtlasCloud"
	ProviderAtoma            = "Atoma"
	ProviderAvian            = "Avian"
	ProviderAzure            = "Azure"
	ProviderBaseTen          = "BaseTen"
	ProviderCerebras         = "Cerebras"
	ProviderChutes           = "Chutes"
	ProviderCloudflare       = "Cloudflare"
	ProviderCohere           = "Cohere"
	ProviderCrofAI           = "CrofAI"
	ProviderCrusoe           = "Crusoe"
	ProviderDeepInfra        = "DeepInfra"
	ProviderDeepSeek         = "DeepSeek"
	ProviderEnfer            = "Enfer"
	ProviderFeatherless      = "Featherless"
	ProviderFireworks        = "Fireworks"
	ProviderFriendli         = "Friendli"
	ProviderGMICloud         = "GMICloud"
	ProviderGoogle           = "Google"
	ProviderGoogleAIStudio   = "Google AI Studio"
	ProviderGroq             = "Groq"
	ProviderInception        = "Inception"
	ProviderInferenceNet     = "InferenceNet"
	ProviderInfermatic       = "Infermatic"
	ProviderInflection       = "Inflection"
	ProviderInoCloud         = "InoCloud"
	ProviderKluster          = "Kluster"
	ProviderLambda           = "Lambda"
	ProviderLiquid           = "Liquid"
	ProviderMeta             = "Meta"
	ProviderMinimax          = "Minimax"
	ProviderMistral          = "Mistral"
	ProviderMorph            = "Morph"
	ProviderNCompass         = "NCompass"
	ProviderNebius           = "Nebius"
	ProviderNextBit          = "NextBit"
	ProviderNineteen         = "Nineteen"
	ProviderNovita           = "Novita"
	ProviderOpenAI           = "OpenAI"
	ProviderOpenInference    = "OpenInference"
	ProviderParasail         = "Parasail"
	ProviderPerplexity       = "Perplexity"
	ProviderPhala            = "Phala"
	ProviderStealth          = "Stealth"
	ProviderSwitchpoint      = "Switchpoint"
	ProviderTargon           = "Targon"
	ProviderUbicloud         = "Ubicloud"
	ProviderVenice           = "Venice"
	ProviderXAI              = "xAI"
)

// Provider shortcuts for common patterns
const (
	ShortcutNitro  = ":nitro"  // Sort by throughput
	ShortcutFloor  = ":floor"  // Sort by price
	ShortcutOnline = ":online" // Enable web search
)